[package]
name = "the_presenter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.7.0"
serde = "1.0.148"
serde_derive = "1.0.148"
toml = "0.5.9"
